server:
    port: 8090

spring:
    application:
        name: microservice-user-consumer


eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.70.250:9101/eureka/


provider:
    url: http://MICROSERVICE-USER-PROVIDER/api/user/

